### ISSUE TITLE
jQuery#identify should just be a getter

### ISSUE THREAD

**Issue by james-jlo-long** [Skateside/jquery-aria#3]
I think `$().identify()` should just be a getter, similar to `$().attr("id")`. This feels a lot more jQuery-esque than the current implementation. Also, `$("#--id--")` is just a direct wrapper for `document.getElementById("--id--")` [as you can see here](https://github.com/jquery/jquery/blob/master/src/core/init.js#L79) so there's no benefit in not using it - may as well get the performance boost.

```js
$.fn.identify = function () {

    var id = this.attr("id");

    if (!id) {

        do {

            id = IDENTIFY_PREFIX + count;
            count += 1;
            
        } while (document.getElementById(id));

        this.attr("id", id);
        
    }

    return id;

};
```

**Comment by Skateside** [comment]
I agree and I've implemented that
